# Generated by Django 2.2.2 on 2019-06-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headlines', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB_Dates',
        ),
    ]
