# Generated by Django 2.2.2 on 2019-06-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='news_category',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
